from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    Custom user model with role-based access control.
    Must be defined before any migrations run (AUTH_USER_MODEL in settings).
    """

    class Role(models.TextChoices):
        ADMIN   = 'admin',   'Admin'
        MANAGER = 'manager', 'Manager'
        STAFF   = 'staff',   'Staff'

    role = models.CharField(
        max_length=20,
        choices=Role.choices,
        default=Role.STAFF,
    )
    phone = models.CharField(max_length=20, blank=True)
    is_active_employee = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.username} ({self.role})"

    @property
    def is_admin(self):
        return self.role == self.Role.ADMIN

    @property
    def is_manager(self):
        return self.role == self.Role.MANAGER

    @property
    def is_manager_or_above(self):
        return self.role in (self.Role.ADMIN, self.Role.MANAGER)


class Product(models.Model):
    """
    Master product table. One row per product (P0001–P0020).
    """

    CATEGORY_CHOICES = [
        ('electronics', 'Electronics'),
        ('clothing',    'Clothing'),
        ('food',        'Food & Groceries'),
        ('home',        'Home & Furniture'),
        ('sports',      'Sports & Outdoors'),
        ('other',       'Toys & Other'),
    ]

    product_id    = models.CharField(max_length=20, unique=True, db_index=True)
    name          = models.CharField(max_length=200)
    category      = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='other')
    price         = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    current_stock = models.IntegerField(default=0)
    reorder_point = models.IntegerField(default=0, help_text='Stock level that triggers a reorder alert')
    is_active     = models.BooleanField(default=True)
    created_at    = models.DateTimeField(auto_now_add=True)
    updated_at    = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['product_id']

    def __str__(self):
        return f"{self.product_id} — {self.name}"

    def days_until_stockout(self, weekly_demand):
        if not weekly_demand or weekly_demand <= 0:
            return None
        return int(self.current_stock / (weekly_demand / 7))

    @property
    def needs_reorder(self):
        return self.current_stock <= self.reorder_point


class ProductForecast(models.Model):
    """
    Weekly demand forecast for a product, generated by Prophet models.
    """

    product_ref = models.ForeignKey(
        Product,
        to_field='product_id',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='forecasts',
        db_column='product_fk',
    )
    product_id         = models.CharField(max_length=20, db_index=True)
    forecast_date      = models.DateField()
    predicted_units    = models.FloatField()
    current_stock      = models.IntegerField(null=True, blank=True)
    days_until_stockout = models.IntegerField(null=True, blank=True)
    generated_at       = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('product_id', 'forecast_date')
        ordering = ['-forecast_date']

    def __str__(self):
        return f"{self.product_id} — {self.forecast_date}: {self.predicted_units:.0f} units"


class AuditLog(models.Model):
    """
    Immutable audit trail — tracks every create/update/delete on Products.
    Used by Manager/Admin views and the AI agentic layer.
    """

    class Action(models.TextChoices):
        CREATE = 'create', 'Create'
        UPDATE = 'update', 'Update'
        DELETE = 'delete', 'Delete'

    user       = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name='audit_logs',
    )
    action     = models.CharField(max_length=10, choices=Action.choices)
    model_name = models.CharField(max_length=50)
    object_id  = models.CharField(max_length=50)
    details    = models.TextField(blank=True)
    timestamp  = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.user} {self.action} {self.model_name} #{self.object_id}"
