from django.db import models


class Product(models.Model):
    """
    Master product table. One row per product (P0001–P0020).
    Stock levels and metadata live here.
    """

    CATEGORY_CHOICES = [
        ('electronics', 'Electronics'),
        ('clothing', 'Clothing'),
        ('food', 'Food & Groceries'),
        ('home', 'Home & Furniture'),
        ('sports', 'Sports & Outdoors'),
        ('other', 'Toys & Other'),
    ]

    product_id = models.CharField(max_length=20, unique=True, db_index=True)
    name = models.CharField(max_length=200)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='other')
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    current_stock = models.IntegerField(default=0)
    reorder_point = models.IntegerField(default=0, help_text='Stock level that triggers a reorder alert')
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['product_id']

    def __str__(self):
        return f"{self.product_id} — {self.name}"

    def days_until_stockout(self, weekly_demand):
        """
        Calculate how many days of stock remain given a weekly demand forecast.
        Returns None if demand is zero to avoid division by zero.
        """
        if not weekly_demand or weekly_demand <= 0:
            return None
        daily_demand = weekly_demand / 7
        return int(self.current_stock / daily_demand)

    @property
    def needs_reorder(self):
        return self.current_stock <= self.reorder_point


class ProductForecast(models.Model):
    """
    Weekly demand forecast for a product, generated by Prophet models.
    Linked to Product via product_id (CharField, not FK) so forecasts
    can be generated even before the Product row exists.
    """

    product_ref = models.ForeignKey(
        Product,
        to_field='product_id',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='forecasts',
        db_column='product_fk',
    )
    product_id = models.CharField(max_length=20, db_index=True)
    forecast_date = models.DateField()
    predicted_units = models.FloatField()
    current_stock = models.IntegerField(null=True, blank=True)
    days_until_stockout = models.IntegerField(null=True, blank=True)
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('product_id', 'forecast_date')
        ordering = ['-forecast_date']

    def __str__(self):
        return f"{self.product_id} — {self.forecast_date}: {self.predicted_units:.0f} units"
