from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView

from .views import (
    CustomTokenObtainPairView,
    MeView,
    UserViewSet,
    ProductViewSet,
    AuditLogViewSet,
    ProductForecastListView,
    ProductForecastDetailView,
)

router = DefaultRouter()
router.register('users',      UserViewSet,     basename='user')
router.register('products',   ProductViewSet,  basename='product')
router.register('audit-logs', AuditLogViewSet, basename='audit-log')

urlpatterns = [
    # Auth
    path('auth/login/',   CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/refresh/', TokenRefreshView.as_view(),          name='token_refresh'),
    path('auth/me/',      MeView.as_view(),                    name='auth_me'),

    # Router-based (users, products, audit-logs)
    path('', include(router.urls)),

    # Forecasts (list-only — generated by management command, not user CRUD)
    path('forecasts/',          ProductForecastListView.as_view(),   name='forecast-list'),
    path('forecasts/<int:pk>/', ProductForecastDetailView.as_view(), name='forecast-detail'),
]
