# Generated by Django 5.2.16 on 2026-07-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=20)),
                ('forecast_date', models.DateField()),
                ('predicted_units', models.FloatField()),
                ('current_stock', models.IntegerField(blank=True, null=True)),
                ('days_until_stockout', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-forecast_date'],
                'unique_together': {('product_id', 'forecast_date')},
            },
        ),
    ]
