# Generated by Django 5.2.16 on 2026-07-15 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food & Beverage'), ('home', 'Home & Garden'), ('sports', 'Sports & Outdoors'), ('other', 'Other')], default='other', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_point', models.IntegerField(default=0, help_text='Stock level that triggers a reorder alert')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product_id'],
            },
        ),
        migrations.AddField(
            model_name='productforecast',
            name='product_ref',
            field=models.ForeignKey(blank=True, db_column='product_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='inventory.product', to_field='product_id'),
        ),
    ]
